### ISSUE TITLE
$files->groupBy() doesn't seem to work

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/kirby#554]

**Comment by LeBenLeBen** [comment]
Indeed, trying to do `$page->files()->groupBy('category')` results in:

```
Whoops\Exception\ErrorException thrown with message "Trying to get property of non-object"

Stacktrace:
#11 Whoops\Exception\ErrorException in /vagrant/kirby/core/files.php:21
#10 Whoops\Run:handleError in /vagrant/kirby/core/files.php:21
#9 FilesAbstract:__construct in /vagrant/kirby/vendor/getkirby/toolkit/lib/collection.php:467
#8 Collection:group in /vagrant/kirby/vendor/getkirby/toolkit/lib/collection.php:496
#7 Collection:groupBy in /vagrant/site/templates/sponsors.php:6
#6 require in /vagrant/kirby/vendor/getkirby/toolkit/lib/tpl.php:22
#5 Tpl:load in /vagrant/kirby/kirby/component/template.php:103
#4 Kirby\Component\Template:render in /vagrant/kirby/kirby.php:635
#3 Kirby:template in /vagrant/kirby/kirby.php:623
#2 Kirby:render in /vagrant/kirby/kirby/component/response.php:29
#1 Kirby\Component\Response:make in /vagrant/kirby/kirby.php:705
#0 Kirby:launch in /vagrant/index.php:16
```

By Blueprint being:

```
title: Sponsors

pages: false

files:
  fields:
    name:
      label: Name
      type: text
    category:
      label: Category
      type: select
      options:
        - other
        - main
        - institutional
        - media
    url:
      label: URL
      type: url
```
