### ISSUE TITLE
Checkbox with `->bool()` always returns false

### ISSUE THREAD

**Issue by heroheman** [getkirby-v2/kirby#627]
**Toolkit version: 2.5.8
Kirby version: 2.5.8
Panel version: 2.5.8** 

If I use a checkbox and use the `bool` field method, it returns false, even when the checkbox is checked. 
I implemented it, similar to the documentation: https://getkirby.com/docs/cheatsheet/panel-fields/checkbox

**not working:**
```
<?php
    if ( $data->background_fixed()->bool()) {
        $fixed = 'section--is-fixed';
    } else {
        $fixed = '';
    }
?>
```

**Working**
```
<?php
    if ( $data->background_fixed() == '1') {
        $fixed = 'section--is-fixed';
    } else {
        $fixed = '';
    }
?>
```

The blueprint (is in a default `yml` file in the `fields` folder)
```
  background_fixed:
    label: Fixed Background?
    text: u could check this, or not
    type:  checkbox
    width: 1/2
```

I checked the `.txt` file in the content folder, and the element is set to `1`.

Additional Information: I used the one-pager implementation from the cookbook. Thats the reason I have a `$data` instead of a `$page`.
