### ISSUE TITLE
translate: false is null when in structure type

### ISSUE THREAD

**Issue by ghost** [getkirby-v2/kirby#638]
Hey there!

My blueprint looks as follows:
```
  entries:
    label: Entries on the Home page
    type: structure
    style: table
    fields:
      title:
        label: Title
        type:  title
        width: 1/2
      pic:
        label: Cover Image
        type: image
        width: 1/2
        translate: false
```
In the default language i can choose the image. When changing to another language, the field is disabled as wished, but it's not saving the default language selection, but saves "null" instead.
